[theme]
base = "light"
primaryColor = "#2C5784"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F8FAFC"
textColor = "#1F2937"
font = "sans serif"

[server]
headless = true
runOnSave = false

[browser]
gatherUsageStats = false
